"""add status column to Ticket

Revision ID: 934477d8c8eb
Revises: 8ab6b9a2c356
Create Date: 2025-11-04 19:41:33.269358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '934477d8c8eb'
down_revision: Union[str, Sequence[str], None] = '8ab6b9a2c356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'status')
    # ### end Alembic commands ###
