"""Test visibility

Revision ID: c0a8c749a2b3
Revises: 934477d8c8eb
Create Date: 2025-11-07 15:04:52.076345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0a8c749a2b3'
down_revision: Union[str, Sequence[str], None] = '934477d8c8eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('probnatabela')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('probnatabela',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('naziv', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('probnatabela_pkey'))
    )
    # ### end Alembic commands ###
