"""Initial tables

Revision ID: fdf6496f01ed
Revises: c0a8c749a2b3
Create Date: 2025-11-09 01:11:02.571392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdf6496f01ed'
down_revision: Union[str, Sequence[str], None] = 'c0a8c749a2b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:  
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('default_rate', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='parking_config_pkey')
    )
    op.create_table('probnatabela',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naziv', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id', name='probnatabela_pkey')
    )
    op.create_table('vehicle_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('rate', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='vehicle_types_pkey'),
    sa.UniqueConstraint('type', name='vehicle_types_type_key')
    )
    op.create_table('tickets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_registration', sa.String(), nullable=False),
    sa.Column('vehicle_type_id', sa.Integer(), nullable=False),
    sa.Column('bar_code', sa.String(), nullable=False),
    sa.Column('entry_time', sa.DateTime(), nullable=True),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('fee', sa.Numeric(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['vehicle_types.id'], name='tickets_vehicle_type_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tickets_pkey'),
    sa.UniqueConstraint('bar_code', name='tickets_bar_code_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    op.drop_table('vehicle_types')
    op.drop_table('probnatabela')
    op.drop_table('parking_config')
    # ### end Alembic commands ###
